### ISSUE TITLE
[Feature Request] Support generalized items and abilities

### ISSUE THREAD

**Issue by boktai1000** [valkyrnstudios/TankBuddy#9]
Awesome! Glad to see this supported - I was wondering if there were some more abilities and trinkets that could be added.

For example, there's a new trinket Regal Protectorate that is similar to Lifegiving Gem. There are also Nightmare Seeds which are a new consumable that can be herbed, but doesn't require Herbalism to use, which is like a mini Last Stand. Additionally an option for Warrior offensives might be nice too, for like Recklessness/Death Wish (even though Fury Prot is RIP - some may be interested in having an announce for that too)

I'm sure there's a plethora of new "Lifegiving" like trinkets and such, and Regal Protectorate is the only one I have that mimics Lifegiving, but I know there's a bunch of other new "Use" trinkets. Do you want us to report them to you, or would maybe a "configurable" trinket option to allow people to set that up be more ideal?

Lastly - even though this is for BCC, did you have any plans to resurrect this for Classic Era? Thanks for the great addon!

**Comment by boktai1000** [comment]
https://tbc.wowhead.com/item=28042/regal-protectorate

**Comment by SabreValkyrn** [comment]
That is indeed something I was intending to support, but a bit busy IRL, pushing for Kara/heroic attunes, and professions so haven't had much time.

https://github.com/valkyrnstudios/TankBuddy/blob/01b4193da2a40f4ed0aeee6e7d65b5e13bcdf248/TankBuddy.lua#L180
https://github.com/valkyrnstudios/TankBuddy/blob/01b4193da2a40f4ed0aeee6e7d65b5e13bcdf248/TankBuddy.lua#L554

I've played TBC as a Prot War for the past 4 years, there are indeed a lot of powerful Use trinkets I'd like supported. I use Regal Protectorate currently as well. TBH, until this addon I didn't know Lifegiving Gem existed since it comes from end-game Classic.

I'd like to generalize trinkets/items (and abilities), much in the same way the buff removal works. That's my next planned feature.

>even though this is for BCC, did you have any plans to resurrect this for Classic Era? 

#10

**Comment by SabreValkyrn** [comment]
I've been pretty busy IRL, barely have time to finish Cooking/Fishing dailies, but I have this mostly functional on a local branch, a few kinks to work out though.

**Comment by SabreValkyrn** [comment]
Supported in 3.0.8
